//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDatabaseLib
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TourismWebsiteDBEntities : DbContext
    {
        public TourismWebsiteDBEntities()
            : base("name=TourismWebsiteDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<BlogSpace> BlogSpaces { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<TouristPlace> TouristPlaces { get; set; }
        public virtual DbSet<UserReview> UserReviews { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Membership> Memberships { get; set; }
    }
}
