//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDatabaseLib
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Package
    {
        public int PackageId { get; set; }
        [Display(Name = "Place Name")]
        public string PlaceName { get; set; }
        [Display(Name = "Days")]
        public Nullable<int> NoOfDays { get; set; }
        [Display(Name = "Nights")]
        public Nullable<int> NoOfNights { get; set; }
        [Display(Name = "Person")]
        public Nullable<int> NoOfPerson { get; set; }
        [Display(Name = "Price")]
        public Nullable<int> Price { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
    }
}
