//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectDatabaseLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReview
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public int Rating { get; set; }
        public Nullable<bool> Isactive { get; set; }
        public int Createdby { get; set; }
    
        public virtual User User { get; set; }
    }
}
